apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uspc-data-pvc
  namespace: uspc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uspc-postgres-pvc
  namespace: uspc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
