apiVersion: v1
kind: Pod
metadata:
  name: uspc-pod
spec:
  containers:
    - name: uspc-headscale
      image: docker.io/headscale/headscale:0.22.3
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale
        - name: headscale-data
          mountPath: /var/lib/headscale
  volumes:
    - name: headscale-config
      hostPath:
        path: ~/.uspc/config/headscale
    - name: headscale-data
      hostPath:
        path: ~/.uspc/data/headscale
