apiVersion: v1
kind: Pod
metadata:
  name: uspc-pod
spec:
  containers:
    - name: uspc-postgres
      image: docker.io/library/postgres:16.1-alpine
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_DB
          value: "nextcloud"
        - name: POSTGRES_USER
          value: "nextcloud"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      hostPath:
        path: ~/.uspc/data/postgres
